name: "Environment setup"
description: "Prepare all the stuff for fastlane build"

# inputs:
#   ruby_version:
#     description: Specify ruby version to use
#     required: true
#   macos_image:
#     description: Mac OS image Version
#     required: true

runs:
  using: "composite"
  steps:
    - name: Clean after
      uses: hathway/actions/post-cleanup@master

    - name: Checkout
      uses: actions/checkout@v3

    - name: Bundler
      shell: bash
      run: |
        bundle config set --local path ~/gems
        bundle install

    # - name: Setup Ruby
    #   uses: ruby/setup-ruby@v1
    #   env:
    #     ImageOS: ${{ inputs.macos_image }}
    #   with:
    #     ruby-version: ${{ inputs.ruby_version }}
    #     bundler-cache: true
